import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// 👇 ADD THIS
import PostHogProvider from "@/libs/PostHogProvider";
import "@/libs/posthog";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Livora Crafts",
  description: "Generated by create next app",
  icons: {
    icon: "/images/image-logo.png",  // ← apna actual logo path
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 👇 WRAP THIS */}
        <PostHogProvider>
          {children}
        </PostHogProvider>
      </body>
    </html>
  );
}