export const products = [
  {
    id: 1,
    category: "coasters",
    name: "Madhubani Bird Motif Hand-Painted Coasters",
    image: "/products/coasters/c-1.webp",
    images: [
      "/products/coasters/c-1.webp",
      "/products/coasters/el-005-1736.webp",
      "/products/coasters/el-005-1736-2.webp",
    ],
    material: "Mango Wood",
    finish: "Hand-Painted Madhubani Art, Natural Bark Edge",
    thickness: "14 mm",
    size: "4 inch diameter (round)",
    shape: "Round",
    setOf: 4,
    usage: "Tea Cups, Coffee Mugs, Glasses, Table Protection",
    packaging: "Export Safe Packaging",
    highlight: "Each coaster is hand-painted with traditional Madhubani bird motifs — no two pieces are identical.",
  },

  {
    id: 2,
    category: "coasters",
    name: "Laser Engraved Botanical Leaf Coasters",
    image: "/products/coasters/c-2.jpg",
    images: [
      "/products/coasters/c-2.jpg",
      "/products/coasters/el-005-373-2.webp",
    ],
    material: "Mango Wood",
    finish: "Laser Engraved, Natural Matte Finish",
    thickness: "8 mm",
    size: "3.9 inch diameter (round)",
    shape: "Round",
    setOf: 4,
    usage: "Tea Cups, Coffee Mugs, Glasses, Table Protection",
    packaging: "Export Safe Packaging",
    highlight: "Precision laser-engraved fern and ginkgo leaf patterns on smooth mango wood.",
  },

  {
    id: 3,
    category: "coasters",
    name: "White Acrylic Geometric Coasters With Wooden Holder",
    image: "/products/coasters/c-3.jpg",
    images: [
      "/products/coasters/c-3.jpg",
      "/products/coasters/c-3.2.jpg",
    ],
    material: "Acrylic + Mango Wood Holder",
    finish: "Gloss White with Navy Blue Resin Inlay",
    thickness: "8 mm",
    size: "4 x 4 inches",
    shape: "Square",
    setOf: 6,
    usage: "Dining Table, Coffee Table, Office Desk",
    packaging: "Export Safe Packaging",
    highlight: "Modern navy-on-white geometric design coasters nestled in a handcrafted mango wood holder.",
  },

  {
    id: 4,
    category: "coasters",
    name: "Chevron Inlay Wooden Coasters",
    image: "/products/coasters/c-4.jpg",
    images: [
      "/products/coasters/c-4.jpg",
      "/products/coasters/c-4.2.jpg",
    ],
    material: "Multi-Wood Inlay (Mango, Sheesham & Pine)",
    finish: "Natural Matte, Hand-Sanded Smooth",
    thickness: "12 mm",
    size: "4 x 4 inches",
    shape: "Square",
    setOf: 4,
    usage: "Whiskey Glasses, Dining Table, Home Bar",
    packaging: "Export Safe Packaging",
    highlight: "Intricate chevron zigzag pattern crafted from three contrasting wood tones — no paint, all natural.",
  },

  {
    id: 5,
    category: "coasters",
    name: "Wood & White Resin Round Coasters",
    image: "/products/coasters/c-5.jpg",
    images: [
      "/products/coasters/c-5.jpg",
      "/products/coasters/c-5.2.jpg",
    ],
    material: "Mango Wood + White Epoxy Resin",
    finish: "Polished High-Gloss Resin with Natural Wood Edge",
    thickness: "10 mm",
    size: "3.9 inch diameter (round)",
    shape: "Round",
    setOf: 6,
    usage: "Mugs, Glasses, Dining Table, Gift Sets",
    packaging: "Jute-Tied Bundle, Export Safe Packaging",
    highlight: "Organic wood grain meets smooth white resin in a stunning half-and-half finish. Comes gift-ready tied in jute.",
  },

  {
    id: 6,
    category: "coasters",
    name: "Wood Cross-Section Dark Epoxy Resin Coasters",
    image: "/products/coasters/c-6.jpg",
    images: [
      "/products/coasters/c-6.jpg",
    ],
    material: "Mango Wood Cross-Sections + Dark Smoky Epoxy Resin",
    finish: "High-Gloss Epoxy, Polished Edges",
    thickness: "15 mm",
    size: "4 x 4 inches",
    shape: "Square",
    setOf: 2,
    usage: "Whiskey Glasses, Bar Table, Statement Decor",
    packaging: "Export Safe Packaging",
    highlight: "Live-edge wood cross-sections suspended in swirling dark grey resin — a conversation piece on every table.",
  },

  {
    id: 7,
    category: "coasters",
    name: "Black Kintsugi Gold Coasters With Holder",
    image: "/products/coasters/c-7.jpg",
    images: [
      "/products/coasters/c-7.jpg",
    ],
    material: "Concrete / Stone Composite",
    finish: "Matte Black with Gold Kintsugi Veining",
    thickness: "10 mm",
    size: "4 inch diameter (round)",
    shape: "Round",
    setOf: 5,
    usage: "Whiskey Glasses, Coffee Mugs, Luxury Home Decor",
    packaging: "Export Safe Packaging with Matching Holder",
    highlight: "Inspired by the Japanese art of Kintsugi — bold black matte finish cracked with hand-applied gold veins. Includes matching black holder.",
  },

  {
    id: 8,
    category: "coasters",
    name: "Hexagonal Marble Swirl Coasters",
    image: "/products/coasters/c-8.jpg",
    images: [
      "/products/coasters/c-8.jpg",
    ],
    material: "Resin / Polymer Marble Composite",
    finish: "Marble Swirl, Smooth Matte Surface",
    thickness: "8 mm",
    size: "4.5 inch width (hexagonal)",
    shape: "Hexagonal",
    setOf: 6,
    usage: "Dining Table, Coffee Table, Luxury Gift Sets",
    packaging: "Export Safe Packaging",
    highlight: "Unique hexagonal form with fluid marble swirl patterns — each piece has a one-of-a-kind pattern in grey, black and gold tones.",
  },

  {
    id: 9,
    category: "coasters",
    name: "Half-Engraved Geometric Star Coasters",
    image: "/products/coasters/c-9.jpg",
    images: [
      "/products/coasters/c-9.jpg",
    ],
    material: "Sheesham Wood (Indian Rosewood)",
    finish: "Natural Wood Grain + Laser Engraved Geometric Pattern",
    thickness: "12 mm",
    size: "4 inch diameter (round)",
    shape: "Round",
    setOf: 4,
    usage: "Tea Cups, Coffee Mugs, Luxury Dining",
    packaging: "Export Safe Packaging",
    highlight: "Half smooth natural grain, half precision-engraved Islamic star tessellation — a striking contrast on dark sheesham wood.",
  },


   // ===========================
  // 🟤 CHOPPING BOARD
  // ===========================
  {
    id: 101,
    category: "chopping-board",
    name: "Juice Groove Chopping Board with Cut-Out Handle",
    image: "/products/chopping-board/cb-1.jpg",
    images: ["/products/chopping-board/b-1.jpg"],
    material: "Mango Wood",
    finish: "Natural Matte, Food-Safe Oil Finish",
    thickness: "20 mm",
    size: "14 x 10 inches",
    features: ["Juice groove border", "Integrated cut-out handle", "Rounded corners"],
    usage: "Kitchen Chopping, Meat Carving, Bread Serving",
    packaging: "Export Safe Packaging",
    highlight: "Functional everyday board with a deep juice groove border and a slot handle for easy carry — built for serious kitchen use.",
  },

  {
    id: 102,
    category: "chopping-board",
    name: "Two-Tone Stripe Chopping Board with Top Handle",
    image: "/products/chopping-board/cb-2.jpg",
    images: ["/products/chopping-board/b-2.jpg"],
    material: "Mango Wood + Sheesham Wood Stripe Inlay",
    finish: "Natural Matte, Hand-Sanded Smooth",
    thickness: "18 mm",
    size: "13 x 9 inches",
    features: ["Contrasting dark stripe inlay", "Top cut-out handle", "Juice groove border"],
    usage: "Chopping, Serving, Kitchen Display",
    packaging: "Export Safe Packaging",
    highlight: "Light mango wood body with two deep sheesham stripe inlays — decorative enough to serve on, sturdy enough to chop on.",
  },

  {
    id: 103,
    category: "chopping-board",
    name: "Large Acacia Chopping Board with Bottom Grip Slot",
    image: "/products/chopping-board/cb-3.jpg",
    images: ["/products/chopping-board/b-3.jpg"],
    material: "Acacia Wood",
    finish: "Natural Matte, Food-Safe Oil Finish",
    thickness: "22 mm",
    size: "16 x 12 inches",
    features: ["Deep juice groove", "Bottom grip slot handle", "Multi-tone natural grain"],
    usage: "Meat Carving, Bread Slicing, Charcuterie Serving",
    packaging: "Export Safe Packaging",
    highlight: "Large-format professional board with acacia's natural multi-tone grain — the bottom slot handle makes it easy to lift and serve.",
  },

  {
    id: 104,
    category: "chopping-board",
    name: "Botanical Wheat Engraved Paddle Serving Board",
    image: "/products/chopping-board/cb-4.jpg",
    images: ["/products/chopping-board/b-4.jpg"],
    material: "Mango Wood",
    finish: "Natural Matte with Pyrography Engraving",
    thickness: "15 mm",
    size: "14 x 6 inches (including handle)",
    features: ["Curved paddle handle with hang hole", "Laser/burn engraved wheat motif", "Live-edge character marks"],
    usage: "Cheese Serving, Charcuterie, Kitchen Wall Decor",
    packaging: "Export Safe Packaging",
    highlight: "Paddle-style board with a delicate wheat stalk burn engraving — doubles as a decorative wall piece when not in use.",
  },

  {
    id: 105,
    category: "chopping-board",
    name: "Round Wine & Cheese Engraved Serving Board",
    image: "/products/chopping-board/cb-5.jpg",
    images: ["/products/chopping-board/b-5.jpg"],
    material: "Mango Wood",
    finish: "Natural Matte, Food-Safe Finish",
    thickness: "15 mm",
    size: "12 inch diameter + 5 inch handle",
    features: ["Round paddle form", "Burn-engraved wine & cheese illustration", "Hang hole on handle"],
    usage: "Wine & Cheese Serving, Charcuterie Board, Gift Sets",
    packaging: "Export Safe Packaging",
    highlight: "Round board with a hand-burned continuous line-art wine bottle, glass and cheese scene — a perfect gifting piece for wine lovers.",
  },

  {
    id: 106,
    category: "chopping-board",
    name: "End-Grain Checkerboard Butcher Block Board",
    image: "/products/chopping-board/cb-6.jpg",
    images: ["/products/chopping-board/b-6.jpg"],
    material: "Teak Wood (End-Grain)",
    finish: "Food-Safe Mineral Oil Finish",
    thickness: "40 mm",
    size: "18 x 14 inches",
    features: ["End-grain construction", "Checkerboard mosaic pattern", "Self-healing surface", "Knife-friendly"],
    usage: "Heavy Duty Chopping, Meat Butchering, Professional Kitchen",
    packaging: "Export Safe Packaging",
    highlight: "Premium end-grain butcher block with a mosaic checkerboard pattern — self-healing surface protects knife edges and resists deep cut marks.",
  },

  {
    id: 107,
    category: "chopping-board",
    name: "Organic Fish-Shape Serving Board with Ring Handle",
    image: "/products/chopping-board/cb-7.jpg",
    images: ["/products/chopping-board/b-7.jpg"],
    material: "Oak Wood",
    finish: "Natural Food-Safe Oil Finish",
    thickness: "18 mm",
    size: "16 x 10 inches (at widest)",
    features: ["Organic oval/leaf silhouette", "Carved ring loop handle", "Hang hole", "Comes with jute tag tie"],
    usage: "Charcuterie Serving, Cheese Board, Kitchen Gifting",
    packaging: "Jute-Tagged, Export Safe Packaging",
    highlight: "Free-form leaf silhouette in European oak with a sculptural ring loop handle — a stunning centrepiece board that arrives gift-ready with a jute tag.",
  },

  // ===========================
  // 🟤 PEN STANDS
  // ===========================

  {
    id: 201,
    category: "pen-holder",
    name: "Split-Slot Minimal Wooden Pen Stand",
    image: "/products/pen-holder/p-1.jpg",
    images: ["/products/pen-holder/p-1.jpg"],
    material: "Beech Wood",
    finish: "Natural Light Matte, Food-Safe Oil",
    size: "3 x 3 x 4 inches",
    capacity: "8–10 pens",
    usage: "Office Desk Organizer, Stationery Holder",
    packaging: "Export Safe Packaging",
    highlight: "Clean two-slot beech wood block with a central divider — a minimal, sturdy pen stand that looks sharp on any desk.",
  },

  {
    id: 202,
    category: "pen-holder",
    name: "Faceted Geometric Polyhedron Pen Cup",
    image: "/products/pen-holder/p-2.jpg",
    images: ["/products/pen-holder/p-2.jpg"],
    material: "Ceramic / Resin Composite",
    finish: "Sand Yellow Matte",
    size: "3.5 inch W x 4.5 inch H",
    capacity: "10–12 pens / brushes",
    usage: "Art Desk, Stationery Organizer, Creative Studio",
    packaging: "Export Safe Packaging",
    highlight: "Multi-faceted diamond-cut form in warm sand yellow matte — a sculptural desk organizer that doubles as a decor object.",
  },

  {
    id: 203,
    category: "pen-holder",
    name: "Elephant Shape Wooden Desk Organizer",
    image: "/products/pen-holder/p-3.jpg",
    images: ["/products/pen-holder/p-3.jpg"],
    material: "Pine Wood",
    finish: "Natural Unfinished Smooth",
    size: "7 inch W x 5 inch H x 3 inch D",
    capacity: "6–8 pens + card slot",
    usage: "Kids Desk, Office Decor, Gifting",
    packaging: "Export Safe Packaging",
    highlight: "Adorable elephant silhouette with a pen slot on the back and a card/phone slot on the side — functional and fun for kids and adults alike.",
  },

  {
    id: 204,
    category: "pen-holder",
    name: "Three-Tier Stacked Ring Wooden Pen Holder",
    image: "/products/pen-holder/p-4.jpg",
    images: ["/products/pen-holder/p-4.jpg"],
    material: "Beech Wood + Maple Wood (two-tone rings)",
    finish: "Natural Matte, Hand-Sanded",
    size: "3 inch diameter x 3.5 inch H",
    capacity: "5–6 pens",
    usage: "Desk Organizer, Minimalist Office Decor",
    packaging: "Export Safe Packaging",
    highlight: "Three lathe-turned wooden rings in alternating light and cream tones stacked on metal pins — an architectural desk piece with Bauhaus character.",
  },

  {
    id: 205,
    category: "pen-holder",
    name: "Ghost Figurine Single Pen Holder",
    image: "/products/pen-holder/p-5.jpg",
    images: ["/products/pen-holder/p-5.jpg"],
    material: "Ceramic / Resin",
    finish: "White Matte Glaze",
    size: "3 inch W x 3.5 inch H",
    capacity: "1 pen / stylus",
    usage: "Desk Decor, Kids Room, Quirky Gift",
    packaging: "Export Safe Packaging",
    highlight: "A friendly ghost figure with arms stretched out to hold your pen — a whimsical desk companion that doubles as a conversation starter.",
  },

  {
    id: 206,
    category: "pen-holder",
    name: "Chick Figurine Ceramic Pen Cup",
    image: "/products/pen-holder/p-6.jpg",
    images: ["/products/pen-holder/p-6.jpg"],
    material: "Ceramic",
    finish: "White Gloss with Yellow Beak & Feet Detail",
    size: "2.8 inch W x 3.5 inch H",
    capacity: "6–8 pens",
    usage: "Kids Desk, Home Office, Cute Gifting",
    packaging: "Export Safe Packaging",
    highlight: "Round chick body in white gloss ceramic with hand-painted yellow beak and feet — an irresistibly cute desk organizer for any age.",
  },

  {
    id: 207,
    category: "pen-holder",
    name: "White Marble Print Square Pen Holder",
    image: "/products/pen-holder/p-7.jpg",
    images: ["/products/pen-holder/p-7.jpg"],
    material: "Resin / PU with Marble Print",
    finish: "White Marble Texture, Rose Gold Interior",
    size: "3 x 3 x 4 inches",
    capacity: "8–10 pens",
    usage: "Office Desk, Makeup Brush Holder, Luxury Stationery",
    packaging: "Export Safe Packaging",
    highlight: "Square form wrapped in a white marble print with a warm rose gold interior — a premium-look desk accessory that suits both offices and vanity tables.",
  },

  {
    id: 208,
    category: "pen-holder",
    name: "Black Metal Wire Cage Pen Holder",
    image: "/products/pen-holder/p-8.jpg",
    images: ["/products/pen-holder/p-8.jpg"],
    material: "Powder-Coated Iron / Steel",
    finish: "Matte Black",
    size: "3.5 inch diameter x 4.5 inch H",
    capacity: "12–15 pens / pencils",
    usage: "Office Desk, Studio, Minimalist Industrial Decor",
    packaging: "Export Safe Packaging",
    highlight: "Open vertical-bar cage cylinder in matte black iron — see-through design makes finding pens effortless while adding an industrial-cool edge to your desk.",
  },


  // ===========================
  // 🟤 PHOTO FRAMES
  // ===========================

  {
    id: 301,
    category: "photo-frames",
    name: "Classic Black Mat Photo Frame with White Mount",
    image: "/products/photo-frame/fr-1.jpg",
    images: ["/products/photo-frame/fr-1.jpg"],
    material: "Engineered Wood / MDF",
    finish: "Matte Black",
    size: "10 x 12 inches (fits 6 x 8 inch photo with white mat)",
    orientation: "Portrait",
    mounting: "Wall or Tabletop",
    usage: "Photo Display, Gallery Wall, Home Office",
    packaging: "Export Safe Packaging",
    highlight: "Slim matte black frame with a thick white mat border — a timeless combination that makes any photo look gallery-worthy.",
  },

  {
    id: 302,
    category: "photo-frames",
    name: "Natural Oak Shadow Box Deep Frame",
    image: "/products/photo-frame/fr-2.jpg",
    images: ["/products/photo-frame/fr-2.jpg"],
    material: "Oak Wood / MDF",
    finish: "Natural Light Oak Grain",
    size: "6 x 8 inches (inner depth: 1.5 inches)",
    orientation: "Portrait",
    mounting: "Tabletop (with back stand)",
    usage: "3D Photo Display, Memorabilia, Pressed Flowers, Keepsakes",
    packaging: "Export Safe Packaging",
    highlight: "Deep shadow box construction in natural oak — ideal for displaying 3D objects, pressed botanicals, medals, or layered art with depth.",
  },

  {
    id: 303,
    category: "photo-frames",
    name: "Dark Walnut Vintage Wood Photo Frame Set",
    image: "/products/photo-frame/fr-3.jpg",
    images: ["/products/photo-frame/fr-3.jpg"],
    material: "Solid Sheesham / Walnut Wood",
    finish: "Dark Walnut Polish, Smooth Matte",
    size: "6 x 8 inches each",
    orientation: "Landscape",
    setOf: 2,
    mounting: "Tabletop",
    usage: "Art Print Display, Photo Gifting, Vintage Home Decor",
    packaging: "Export Safe Packaging",
    highlight: "Pair of classic dark walnut frames with thin profile and visible wood grain — sold as a set of two for complementary side-by-side display.",
  },

  {
    id: 304,
    category: "photo-frames",
    name: "Ultra-Slim Minimal Square Wall Frame",
    image: "/products/photo-frame/fr-4.jpg",
    images: ["/products/photo-frame/fr-4.jpg"],
    material: "Metal / Powder-Coated Steel",
    finish: "Matte Black, Hair-Thin Profile",
    size: "14 x 14 inches",
    orientation: "Square",
    mounting: "Wall Mount",
    usage: "Modern Gallery Wall, Canvas Art Display, Minimalist Interiors",
    packaging: "Export Safe Packaging",
    highlight: "Barely-there thin metal profile that disappears into the wall — lets the artwork speak. A pure modernist framing solution.",
  },

  {
    id: 305,
    category: "photo-frames",
    name: "Classic Moulded Square Photo Frame",
    image: "/products/photo-frame/fr-5.jpg",
    images: ["/products/photo-frame/fr-5.jpg"],
    material: "MDF / Engineered Wood",
    finish: "Matte Black with Subtle Ridge Moulding",
    size: "12 x 12 inches",
    orientation: "Square",
    mounting: "Wall Mount or Tabletop",
    usage: "Home Decor, Office, Gallery Wall",
    packaging: "Export Safe Packaging",
    highlight: "Slightly moulded ridge profile adds a classic dimension to the matte black frame — works beautifully as a solo statement or in a gallery cluster.",
  },

  {
    id: 306,
    category: "photo-frames",
    name: "Bone & Black Stripe Inlay Photo Frame",
    image: "/products/photo-frame/pf-1.jpeg",
    images: ["/products/photo-frame/pf-1.jpeg"],
    material: "Mango Wood + Bone & Resin Stripe Inlay + Brass Accent",
    finish: "Natural Bone White with Black Stripe Inlay, Gold Brass Bar Detail",
    size: "4 x 6 inches (photo size)",
    orientation: "Portrait",
    mounting: "Tabletop (leather easel back)",
    usage: "Luxury Gifting, Bedside Table, Dining Sideboard Display",
    packaging: "Export Safe Packaging",
    highlight: "Handcrafted in India — bone and black resin stripe inlay with delicate brass bar accents on a mango wood base. A true artisan luxury piece.",
  },

  {
    id: 307,
    category: "photo-frames",
    name: "White & Grey Striped Resin Corner-Block Frame",
    image: "/products/photo-frame/pf-2.jpeg",
    images: ["/products/photo-frame/pf-2.jpeg"],
    material: "Resin / Bone Composite with Ribbed Grey Corner Blocks",
    finish: "Cream White Smooth + Textured Charcoal Corner Inlay",
    size: "4 x 6 inches (photo size)",
    orientation: "Portrait",
    mounting: "Tabletop",
    usage: "Desk Display, Gifting, Boutique Hotel Styling",
    packaging: "Export Safe Packaging",
    highlight: "Cream resin frame with hand-ribbed charcoal grey corner blocks — a bold two-tone contrast that gives a classic frame a contemporary artisan edge.",
  },
  // ===========================
  // 🟤 SERVING PLATTERS
  // ===========================
  {
    id: 401,
    category: "serving-trays",
    name: "White Marble Serving Tray with Brass Bar Handles",
    image: "/products/platters/s-1.jpg",
    images: ["/products/serving-trays/s-1.jpg"],
    material: "White Carrara Marble + Brass / Gold-Plated Metal Handles",
    finish: "Polished Marble with Satin Brass Handles",
    thickness: "15 mm",
    size: "14 x 10 inches",
    usage: "Luxury Serving, Coffee Table Styling, Vanity Tray",
    packaging: "Export Safe Packaging",
    highlight: "Sleek white marble slab with two cylindrical satin brass bar handles — a hotel-lobby level luxury tray for modern homes.",
  },

  {
    id: 402,
    category: "serving-trays",
    name: "Green Floral Bone Inlay Serving Tray Set",
    image: "/products/platters/s-2.jpg",
    images: ["/products/serving-trays/s-2.jpg"],
    material: "Mango Wood + Bone & Resin Inlay",
    finish: "Green & Cream Bone Inlay with Floral Mandala Pattern",
    thickness: "20 mm",
    size: "Large: 16 x 12 inches | Small: 13 x 9 inches",
    setOf: 2,
    usage: "Serving, Decorative Tray, Gifting, Dining Table",
    packaging: "Export Safe Packaging",
    highlight: "Hand-inlaid bone and resin in a dense floral mandala — deep forest green on cream. Sold as a nested set of two, handcrafted in India.",
  },

  {
    id: 403,
    category: "serving-trays",
    name: "Jali Carved Wooden Serving Tray with Star Lattice",
    image: "/products/platters/s-3.jpg",
    images: ["/products/serving-trays/s-3.jpg"],
    material: "Sheesham Wood (Indian Rosewood)",
    finish: "Natural Warm Brown, Hand-Sanded Smooth",
    thickness: "22 mm",
    size: "15 x 11 inches",
    usage: "Serving, Table Decor, Traditional Indian Gifting",
    packaging: "Export Safe Packaging",
    highlight: "Pierced jali lattice walls with Islamic star cutout pattern and integrated hand-grip holes — a truly artisan Indian craft tray.",
  },

  {
    id: 404,
    category: "serving-trays",
    name: "Scallop Edge & Ribbed Wooden Tray Set",
    image: "/products/platters/s-4.jpg",
    images: ["/products/serving-trays/s-4.jpg"],
    material: "Acacia / Mango Wood",
    finish: "Natural Warm Brown Matte Oil Finish",
    thickness: "18 mm",
    size: "Large (scallop): 14 x 14 inches | Small (rectangular): 11 x 7 inches",
    setOf: 2,
    usage: "Breakfast Tray, Coffee Table, Vanity, Snack Serving",
    packaging: "Export Safe Packaging",
    highlight: "Two complementary trays — a cloud-edge scalloped base and a ribbed-texture rectangular insert. Stackable and beautifully organic.",
  },

  {
    id: 405,
    category: "serving-trays",
    name: "Paddle Board Serving Tray with Tile Insert & 3 Bowls",
    image: "/products/platters/s-5.jpg",
    images: ["/products/serving-trays/s-5.jpg"],
    material: "Sheesham Wood + Ceramic Tile Insert + 3 Wooden Bowls",
    finish: "Dark Walnut with Hand-Block Printed Floral Tile",
    thickness: "20 mm",
    size: "16 x 10 inches (board) | 3 inch diameter (each bowl)",
    setOf: 4,
    usage: "Snack Serving, Charcuterie, Gifting, Festive Table",
    packaging: "Export Safe Packaging",
    highlight: "Dark sheesham paddle board with a hand-block printed ceramic tile inlay and 3 matching wooden bowls — a complete artisan serving set, gift-ready.",
  },

  {
    id: 406,
    category: "serving-trays",
    name: "Hourglass Curved Walnut Serving Tray",
    image: "/products/platters/s-6.jpg",
    images: ["/products/serving-trays/s-6.jpg"],
    material: "Walnut Wood",
    finish: "Natural Matte Oil Finish, Two-Tone Grain",
    thickness: "18 mm",
    size: "14 x 9 inches",
    usage: "Breakfast Tray, Coffee Table, Bread & Snack Serving",
    packaging: "Export Safe Packaging",
    highlight: "Sculptural hourglass-waist silhouette carved from walnut — the pinched curves give a classic tray an organic, architectural character.",
  },

  {
    id: 407,
    category: "serving-trays",
    name: "Two-Section Divided Paddle Serving Board with Ring Handle",
    image: "/products/platters/s-7.jpg",
    images: ["/products/serving-trays/s-7.jpg"],
    material: "Oak Wood",
    finish: "Natural Matte Food-Safe Oil Finish",
    thickness: "20 mm",
    size: "20 x 7 inches (including handle)",
    sections: 2,
    usage: "Cheese & Charcuterie Board, Nuts & Snacks, Wine Pairing",
    packaging: "Export Safe Packaging",
    highlight: "Long paddle board with two carved recessed compartments and a ring-loop handle with jute tie — the ideal wine-and-cheese serving board, arrives gift-ready.",
  },

  // ===========================
  // 🟤 WOODEN GAMES
  // ===========================

  {
    id: 501,
    category: "wooden-games",
    name: "Wooden Tic Tac Toe",
    image: "/products/games/g-1.JPG",
    images: ["/products/games/g-1.jpg", "/products/games/g-1-2.jpg"],
    material: "Wood",
    finish: "Matte",
    usage: "Table Game",
    packaging: "Export Pack",
  },

  {
    id: 502,
    category: "wooden-games",
    name: "Wooden Chess Set",
    image: "/products/games/g-2.JPG",
    images: ["/products/games/g-2.jpg", "/products/games/g-2-2.jpg"],
    material: "Sheesham Wood",
    finish: "Polished",
    usage: "Luxury Game",
    packaging: "Protective Box",
  },

  {
    id: 503,
    category: "wooden-games",
    name: "Wooden Puzzle Game",
    image: "/products/games/g-3.JPG",
    images: ["/products/games/g-3.jpg", "/products/games/g-3-2.jpg"],
    material: "Mango Wood",
    finish: "Smooth",
    usage: "Brain Game",
    packaging: "Safe Pack",
  },

  {
    id: 504,
    category: "wooden-games",
    name: "Wooden Domino Set",
    image: "/products/games/g-4.JPG",
    images: ["/products/games/g-4.jpg", "/products/games/g-4-2.jpg"],
    material: "Wood",
    finish: "Matte",
    usage: "Board Game",
    packaging: "Export Pack",
  },

  // ===========================
// 🟤 STORAGE BOXES
// ===========================
  {
    id: 601,
    category: "storage-boxes",
    name: "Bone Inlay Tropical Leaf Print Storage Box",
    image: "/products/storage-boxes/sb-1.jpeg",
    images: ["/products/storage-boxes/sb-1.jpeg"],
    material: "Mango Wood + Bone Inlay Tile Mosaic",
    finish: "Natural Bone White with Teal Stripe Band & Botanical Print Lid",
    size: "10 x 7 x 4 inches",
    closure: "Hinged Lid",
    usage: "Jewelry Storage, Keepsake Box, Luxury Gifting, Vanity Display",
    packaging: "Export Safe Packaging",
    highlight: "Hand-laid bone tile mosaic body with a teal inlay accent band — the lid features a painted tropical leaf botanical print. A statement luxury box crafted in India.",
  },

  {
    id: 602,
    category: "storage-boxes",
    name: "Blue Moroccan Geometric Bone Inlay Box",
    image: "/products/storage-boxes/sb-2.jpg",
    images: ["/products/storage-boxes/sb-2.jpg"],
    material: "Mango Wood + Bone & Resin Inlay",
    finish: "Cobalt Blue & Cream Geometric Pattern, All-Over Inlay",
    size: "8 x 6 x 4 inches",
    closure: "Hinged Lid",
    usage: "Jewelry Box, Trinket Storage, Decorative Keepsake",
    packaging: "Export Safe Packaging",
    highlight: "Intricate Moroccan star-and-petal geometric pattern covers every surface in cobalt blue and ivory bone inlay — a fully handcrafted Indian export piece.",
  },

  {
    id: 603,
    category: "storage-boxes",
    name: "Natural Pine Open Box with Acrylic Slide Lid",
    image: "/products/storage-boxes/st-1.jpg",
    images: ["/products/storage-boxes/st-1.jpg"],
    material: "Pine Wood + Clear Acrylic Lid",
    finish: "Natural Unfinished Pine, Smooth Sanded",
    size: "6 x 5 x 3.5 inches",
    closure: "Sliding Acrylic Transparent Lid",
    usage: "Desk Storage, Stationery Organizer, Craft Supplies",
    packaging: "Export Safe Packaging",
    highlight: "Unfinished natural pine box with a clear acrylic sliding lid — see-through top lets you find contents instantly. Clean, minimal Japanese aesthetic.",
  },

  {
    id: 604,
    category: "storage-boxes",
    name: "Hand-Carved Sheesham Box with Bone Inlay Medallion",
    image: "/products/storage-boxes/st-2.jpg",
    images: ["/products/storage-boxes/st-2.jpg"],
    material: "Sheesham Wood (Indian Rosewood) + Bone Inlay",
    finish: "Dark Walnut Polish with All-Over Floral Hand Carving",
    size: "7 x 5 x 3 inches",
    closure: "Hinged Lid",
    usage: "Jewelry & Keepsake Storage, Gifting, Heritage Decor",
    packaging: "Export Safe Packaging",
    highlight: "Deep-relief hand-carved floral lattice covers the entire box with a central oval bone inlay leaf medallion — traditional Indian craftsmanship at its finest.",
  },

  {
    id: 605,
    category: "storage-boxes",
    name: "Bamboo Incense Stick Box with Lattice Carved Lid",
    image: "/products/storage-boxes/st-3.jpg",
    images: ["/products/storage-boxes/st-3.jpg"],
    material: "Natural Bamboo",
    finish: "Natural Bamboo with Laser-Carved Geometric Lattice Lid",
    size: "11 x 3 x 2 inches",
    closure: "Slide-Off Lattice Lid",
    usage: "Incense Stick Storage, Pen/Brush Box, Meditation Accessories",
    packaging: "Export Safe Packaging",
    highlight: "Long bamboo box with a precision laser-carved triangular lattice pattern on the removable lid — designed for incense sticks but ideal as a luxury pen box too.",
  },

  {
    id: 606,
    category: "storage-boxes",
    name: "Color-Block Patchwork Wood & Lacquer Storage Box",
    image: "/products/storage-boxes/st-4.jpg",
    images: ["/products/storage-boxes/st-4.jpg"],
    material: "Teak Wood + Black Lacquer + White Resin + Gold Brass Panel",
    finish: "Colour-Block Patchwork — Natural Teak, Matte Black, Cream White, Satin Gold",
    size: "11 x 7 x 4 inches",
    closure: "Hinged Lid",
    usage: "Decorative Storage, Coffee Table Box, Luxury Gifting",
    packaging: "Export Safe Packaging",
    highlight: "Bold colour-block design combining natural teak grain, matte black lacquer, white resin and a gold brass panel — a designer-feel box with gallery-shelf presence.",
  },

  {
    id: 607,
    category: "storage-boxes",
    name: "Natural Pine Clasp Box with Brass Lock",
    image: "/products/storage-boxes/st-5.jpg",
    images: ["/products/storage-boxes/st-5.jpg"],
    material: "Pine Wood",
    finish: "Natural Unfinished Pine, Smooth Sanded",
    size: "9 x 7 x 4 inches",
    closure: "Hinged Lid with Gold Brass Toggle Clasp",
    usage: "Jewelry & Keepsake Storage, Stationery, DIY Craft Box",
    packaging: "Export Safe Packaging",
    highlight: "Classic unfinished pine wood box with a gold brass clasp latch — a clean blank-canvas piece ideal for personalisation, decoupage, or natural gifting.",
  },

// 🟤 GLOBES
{
  id: 601,
  category: "globes",
  slug: "wooden-decor-globe",
  name: "Wooden Decor Globe",
  image: "/products/globe/001 (1).jpg",
  images: [
    "/products/globes/g-1.jpg",
    "/products/globes/g-1-2.jpg",
  ],
  material: "Solid Wood",
  finish: "Matte Natural",
  size: "8 inches",
  usage: "Home Decor, Office Styling",
  packaging: "Export Safe Packaging",
},

{
  id: 602,
  category: "globes",
  slug: "vintage-world-globe",
  name: "Vintage World Globe",
  image: "/products/globe/002 (1).jpg",
  images: [
    "/products/globes/g-2.jpg",
    "/products/globes/g-2-2.jpg",
  ],
  material: "Wood & Metal",
  finish: "Antique Finish",
  size: "10 inches",
  usage: "Decor Accent, Study Room",
  packaging: "Protective Packaging",
},

{
  id: 603,
  category: "globes",
  slug: "classic-desk-globe",
  name: "Classic Desk Globe",
  image: "/products/globe/003 (1).jpg",
  images: [
    "/products/globes/g-3.jpg",
    "/products/globes/g-3-2.jpg",
  ],
  material: "Wood Base & Metal Stand",
  finish: "Gloss Finish",
  size: "9 inches",
  usage: "Office Desk, Study",
  packaging: "Export Quality Packaging",
},

{
  id: 604,
  category: "globes",
  slug: "luxury-antique-globe",
  name: "Luxury Antique Globe",
  image: "/products/globe/004 (1).jpg",
  images: [
    "/products/globes/g-4.jpg",
    "/products/globes/g-4-2.jpg",
  ],
  material: "Solid Wood & Brass",
  finish: "Antique Polish",
  size: "12 inches",
  usage: "Luxury Home Decor",
  packaging: "Secure Export Packaging",
},

// ===========================
// 🟤 NAPKIN HOLDERS
// ===========================
  {
    id: 701,
    category: "napkin-holders",
    name: "Open Square Napkin Caddy with V-Cut Front",
    image: "/products/napkin-holders/n-1.jpg",
    images: ["/products/napkin-holders/n-1.jpg"],
    material: "Walnut / Oak Wood",
    finish: "Natural Warm Matte, Smooth Sanded",
    size: "6 x 6 x 3.5 inches",
    capacity: "50–60 napkins",
    usage: "Dining Table, Kitchen Counter, Café",
    packaging: "Export Safe Packaging",
    highlight: "Clean open-top square caddy with a V-notch cutout on the front face for easy napkin pull — minimal Japandi design that suits any dining setting.",
  },

  {
    id: 702,
    category: "napkin-holders",
    name: "Triangular Prism Wooden Napkin Stand",
    image: "/products/napkin-holders/n-2.jpg",
    images: ["/products/napkin-holders/n-2.jpg"],
    material: "Oak Wood + Sheesham Wood (two-tone set)",
    finish: "Light Natural Oak & Dark Walnut — sold as a pair",
    size: "7 x 2 x 4 inches each",
    capacity: "30–40 napkins",
    setOf: 2,
    usage: "Dining Table, Restaurant Styling, Desk Stationery",
    packaging: "Export Safe Packaging",
    highlight: "Angular triangular prism form that props napkins at a natural lean — the two-tone pair in light oak and dark walnut creates beautiful contrast on any table.",
  },

  {
    id: 703,
    category: "napkin-holders",
    name: "Dark Walnut Napkin Dispenser with Lift-Off Lid",
    image: "/products/napkin-holders/n-3.jpg",
    images: ["/products/napkin-holders/n-3.jpg"],
    material: "Sheesham Wood (Indian Rosewood)",
    finish: "Dark Walnut Polish, Smooth Matte",
    size: "6 x 4 x 5 inches",
    capacity: "50–60 napkins",
    usage: "Dining Table, Kitchen Counter, Premium Hospitality",
    packaging: "Export Safe Packaging",
    highlight: "Solid dark walnut box with a fully removable curved-top lid — napkins fan out cleanly from the diagonal opening. A refined desktop dispensing solution.",
  },

  {
    id: 704,
    category: "napkin-holders",
    name: "Mountain Peak Laser-Engraved Napkin Holder",
    image: "/products/napkin-holders/n-4.jpg",
    images: ["/products/napkin-holders/n-4.jpg"],
    material: "MDF / Plywood (Laser Cut)",
    finish: "Walnut Brown or Matte Black — available in both",
    size: "8 x 1.5 x 4.5 inches",
    capacity: "30–40 napkins",
    usage: "Restaurant Branding, Café Table, Corporate Gifting",
    packaging: "Export Safe Packaging",
    customisation: "Custom logo or text laser-engraved on request",
    highlight: "Mountain silhouette napkin holder with a snow-cap cutout — available in walnut or black with custom laser-engraved logo. Perfect for branded restaurant table setups.",
  },

  {
    id: 705,
    category: "napkin-holders",
    name: "Spiral-Cut Dark Walnut Paper Towel Holder",
    image: "/products/napkin-holders/n-6.jpg",
    images: ["/products/napkin-holders/n-6.jpg"],
    material: "Sheesham Wood (Indian Rosewood)",
    finish: "Dark Walnut Matte Polish",
    size: "5 inch diameter x 6 inch H",
    usage: "Kitchen Counter, Paper Towel Roll Holder, Countertop Organizer",
    packaging: "Export Safe Packaging",
    highlight: "Sculptural cylinder with a spiral-cut slot and centre metal rod — holds a standard paper towel roll upright in style. A functional kitchen piece with a premium feel.",
  },

  {
    id: 706,
    category: "napkin-holders",
    name: "Dark Wood Square Napkin Tray with Steel Press Bar",
    image: "/products/napkin-holders/n-7.jpg",
    images: ["/products/napkin-holders/n-7.jpg"],
    material: "Sheesham Wood + Stainless Steel Press Bar",
    finish: "Dark Espresso Matte Wood + Polished Chrome Bar",
    size: "6.5 x 6.5 x 2.5 inches",
    capacity: "40–50 napkins",
    usage: "Dining Table, Restaurant, Hotel Table Setting",
    packaging: "Export Safe Packaging",
    highlight: "Open-frame square tray in dark espresso wood with a ball-tipped stainless steel U-press bar that keeps napkins neatly weighted — a classic hospitality-grade piece.",
  },

// ===========================
// 🟤 DECOR
// ===========================
  {
    id: 705,
    category: "decor-objects",
    name: "Organic Wood Slice Arc Vase with Circular Cutout",
    image: "/products/decor-objects/d-1.jpg",
    images: ["/products/decor-objects/d-1.jpg"],
    material: "Solid Teak / Mango Wood",
    finish: "Natural Oil Finish, Exposed Tree Ring Grain",
    size: "8 inch W x 5 inch H",
    type: "Single Stem Vase",
    usage: "Table Decor, Dried Flower Display, Shelf Styling",
    packaging: "Export Safe Packaging",
    highlight: "Hand-carved from a natural wood cross-section — the circular cutout and visible tree rings make every piece completely one of a kind.",
  },

  {
    id: 706,
    category: "decor-objects",
    name: "Square Frame Wood Vase with Glass Test Tube",
    image: "/products/decor-objects/d-2.jpg",
    images: ["/products/decor-objects/d-2.jpg"],
    material: "Beech Wood + Borosilicate Glass Tube",
    finish: "Natural Light Matte Finish",
    size: "4 x 4 inches",
    type: "Propagation / Single Stem Vase",
    usage: "Desk Decor, Bedside Table, Fresh Flower Propagation",
    packaging: "Export Safe Packaging",
    highlight: "Rounded-corner square beech wood frame holds a removable glass test tube — clean Japandi aesthetic, perfect for a single fresh stem.",
  },

  {
    id: 707,
    category: "decor-objects",
    name: "Wooden Face Spectacles Holder Stand",
    image: "/products/decor-objects/d-3.jpg",
    images: ["/products/decor-objects/d-3.jpg"],
    material: "Sheesham Wood (Indian Rosewood)",
    finish: "Dark Walnut Matte Finish",
    size: "4 inch H x 3 inch W",
    type: "Desk Organiser",
    usage: "Eyeglass Holder, Desk Decor, Office Accessory",
    packaging: "Export Safe Packaging",
    highlight: "Hand-turned abstract face form with a protruding nose to hold glasses — a quirky desk companion that combines function with artisan charm.",
  },

  {
    id: 708,
    category: "decor-objects",
    name: "Abstract Trunk-Up Elephant Wood Sculpture",
    image: "/products/decor-objects/d-4.jpg",
    images: ["/products/decor-objects/d-4.jpg"],
    material: "Sheesham Wood (Indian Rosewood)",
    finish: "Deep Dark Walnut, Hand-Polished",
    size: "4 inch W x 8 inch H",
    type: "Decorative Sculpture",
    usage: "Shelf Decor, Mantelpiece, Gifting",
    packaging: "Export Safe Packaging",
    highlight: "Minimalist abstract silhouette of an elephant with trunk raised high — a symbol of good luck, carved and polished in rich dark sheesham.",
  },

  {
    id: 709,
    category: "decor-objects",
    name: "Interlocking Rings Wooden Knot Sculpture",
    image: "/products/decor-objects/d-5.jpg",
    images: ["/products/decor-objects/d-5.jpg"],
    material: "Mango Wood",
    finish: "Natural Warm Brown, Smooth Matte",
    size: "4 x 4 x 4 inches",
    type: "Decorative Sculpture / Table Object",
    usage: "Coffee Table Decor, Bookshelf Accent, Gifting",
    packaging: "Export Safe Packaging",
    highlight: "Four interlocking wooden rings hand-carved from a single block — a mesmerising sculptural knot that questions how it was ever made.",
  },

  {
    id: 710,
    category: "decor-objects",
    name: "Dark Bronze Abstract Flame Ceramic Sculpture",
    image: "/products/decor-objects/d-6.jpg",
    images: ["/products/decor-objects/d-6.jpg"],
    material: "Ceramic / Resin",
    finish: "Dark Bronze / Black High-Gloss Glaze",
    size: "6 inch W x 11 inch H",
    type: "Decorative Vase / Sculpture",
    usage: "Living Room Decor, Mantelpiece, Statement Shelf Piece",
    packaging: "Export Safe Packaging",
    highlight: "Fluid teardrop loop form in a deep dark bronze glaze — where sculpture meets vase. A dramatic centrepiece with a luxe metallic sheen.",
  },

  {
    id: 711,
    category: "decor-objects",
    name: "Embracing Couple Figurine Vase",
    image: "/products/decor-objects/d-7.jpg",
    images: ["/products/decor-objects/d-7.jpg"],
    material: "Ceramic / Resin",
    finish: "White Matte Glaze",
    size: "4 inch W x 8 inch H",
    type: "Figurine Vase",
    usage: "Table Decor, Wedding Gift, Valentine Gifting",
    packaging: "Export Safe Packaging",
    highlight: "Two intertwined human figures form a vase — the open hands at the top hold a single stem. An iconic gifting piece for couples and homemakers.",
  },

  {
    id: 712,
    category: "decor-objects",
    name: "Olive Abstract Organic Loop Sculpture",
    image: "/products/decor-objects/d-8.jpg",
    images: ["/products/decor-objects/d-8.jpg"],
    material: "Ceramic / Sandstone Composite",
    finish: "Olive / Sage Matte Textured Finish",
    size: "5 inch W x 9 inch H",
    type: "Abstract Sculpture",
    usage: "Shelf Styling, Living Room Decor, Minimalist Interiors",
    packaging: "Export Safe Packaging",
    highlight: "Fluid organic form with multiple open loops on a square plinth — an earthy sage-toned sculpture that brings biophilic calm to any space.",
  },

  {
    id: 713,
    category: "decor-objects",
    name: "Botanical Leaf Sprout Ceramic Sculpture",
    image: "/products/decor-objects/d-9.jpg",
    images: ["/products/decor-objects/d-9.jpg"],
    material: "Ceramic / Sandstone Composite",
    finish: "Olive / Sage Matte Textured Finish",
    size: "3.5 inch W x 8 inch H",
    type: "Decorative Sculpture",
    usage: "Desk Decor, Shelf Styling, Nature-Themed Interiors",
    packaging: "Export Safe Packaging",
    highlight: "A sprouting branch with five sculpted leaves on a square plinth — a serene nature-inspired object in warm earthy sage. Perfect companion to d-8.",
  },

  {
    id: 714,
    category: "decor-objects",
    name: "Infinity Loop Cream & Gold Sculpture Set",
    image: "/products/decor-objects/d-10.jpg",
    images: ["/products/decor-objects/d-10.jpg"],
    material: "Ceramic / Resin",
    finish: "Cream / Off-White Matte with Gold Metallic Sphere",
    size: "Small: 5 inch H | Large: 6.5 inch H",
    type: "Decorative Sculpture Pair",
    setOf: 2,
    usage: "Coffee Table Styling, Living Room Decor, Luxury Gifting",
    packaging: "Export Safe Packaging",
    highlight: "Twin infinity-loop forms in cream matte ceramic, each cradling a polished gold sphere at the base — a sophisticated sculptural pair for modern interiors.",
  },

// ===========================
// 🟤 ORGANIZERS
// ===========================

{
  id: 710,
  category: "desk-organizers",
  name: "Wooden Desk Organizer Tray With Pen Holder",
  image: "/products/desk-organizers/o-11.webp",
  images: [
    "/products/desk-organizers/o-1.webp",
    "/products/desk-organizers/o-1.webp"
  ],
  material: "Solid Wood",
  finish: "Natural Matte",
  size: "12 x 8 inches",
  usage: "Desk Organizer, Watch & Accessories Storage",
  packaging: "Export Safe Packaging",
},

{
  id: 711,
  category: "desk-organizers",
  name: "Leather Multi Section Desk Organizer",
  image: "/products/desk-organizers/o-2.webp",
  images: [
    "/products/desk-organizers/o-2.webp",
    "/products/desk-organizers/o-2-2.webp"
  ],
  material: "PU Leather & Wood",
  finish: "Premium Leather Finish",
  size: "9 x 5 inches",
  usage: "Office Desk Organizer",
  packaging: "Protective Packaging",
},

{
  id: 712,
  category: "desk-organizers",
  name: "Minimal Multi Slot Desk Organizer",
  image: "/products/desk-organizers/o-3.webp",
  images: [
    "/products/desk-organizers/o-3.webp",
  ],
  material: "Engineered Wood",
  finish: "Textured Matte",
  size: "8 x 4 inches",
  usage: "Pen Holder, Card Organizer",
  packaging: "Export Safe Packaging",
},

{
  id: 713,
  category: "desk-organizers",
  name: "Bamboo Desk Organizer With Pen Holder",
  image: "/products/desk-organizers/o-41.webp",
  images: [
    "/products/desk-organizers/o-4.webp",
    "/products/desk-organizers/o-4-2.webp"
  ],
  material: "Bamboo Wood",
  finish: "Natural Matte",
  size: "7 x 4 inches",
  usage: "Desk Storage",
  packaging: "Export Safe Packaging",
},

{
  id: 714,
  category: "desk-organizers",
  name: "Wooden Multi Compartment Desk Organizer",
  image: "/products/desk-organizers/o-51.webp",
  images: [
    "/products/desk-organizers/o-5.webp",
  ],
  material: "Solid Wood",
  finish: "Natural Matte",
  size: "10 x 4 inches",
  usage: "Workspace Organizer",
  packaging: "Export Safe Packaging",
},

{
  id: 715,
  category: "phone-holder",
  name: "Minimal Wooden Phone Dock Stand",
  image: "/products/phone-stand/p-1.jpg",
  images: [
    "/products/phone-stand/p-1.jpg"
  ],
  material: "Solid Wood",
  finish: "Natural Matte",
  size: "5 x 3 inches",
  usage: "Phone Stand, Desk Viewing",
  packaging: "Export Safe Packaging",
},

{
  id: 716,
  category: "phone-holder",
  name: "Wooden Adjustable Phone Stand",
  image: "/products/phone-stand/p-2.jpg",
  images: [
    "/products/phone-stand/p-2.jpg"
  ],
  material: "Sheesham Wood",
  finish: "Smooth Matte Finish",
  size: "6 x 4 inches",
  usage: "Mobile Holder, Desk Viewing Stand",
  packaging: "Protective Packaging",
},

{
  id: 717,
  category: "phone-holder",
  name: "Minimal Wooden Elephant Phone Stand",
  image: "/products/phone-stand/p-3.webp",
  images: [
    "/products/phone-stand/p-3.webp"
  ],
  material: "Beech Wood",
  finish: "Natural Matte",
  size: "4 inches",
  usage: "Phone Holder, Desk Decor",
  packaging: "Export Safe Packaging",
},

{
  id: 718,
  category: "phone-holder",
  name: "Wooden Yoga Phone Holder Stand",
  image: "/products/phone-stand/p-4.jpg",
  images: [
    "/products/phone-stand/p-4.jpg"
  ],
  material: "Beech Wood",
  finish: "Smooth Natural Finish",
  size: "6 inches",
  usage: "Phone Holder, Desk Decor",
  packaging: "Protective Packaging",
},

{
  id: 719,
  category: "phone-holder",
  name: "Wooden Phone Dock With Tray",
  image: "/products/phone-stand/p-5.jpg",
  images: [
    "/products/phone-stand/p-5.jpg"
  ],
  material: "Walnut Wood",
  finish: "Natural Matte",
  size: "7 x 4 inches",
  usage: "Phone Stand, Accessories Tray",
  packaging: "Export Safe Packaging",
},
  {
    id: 720,
    category: "candle-holders",
    name: "Dark Walnut Hourglass Pillar Candle Holder Set",
    image: "/products/candle-holders/h-1.webp",
    images: ["/products/candle-holders/h-1.webp"],
    material: "Sheesham Wood (Indian Rosewood)",
    finish: "Dark Walnut Matte Finish",
    size: "Small: 5 inch H | Large: 7 inch H",
    candleType: "Pillar Candle",
    setOf: 2,
    usage: "Table Decor, Mantelpiece, Dining Centrepiece",
    packaging: "Export Safe Packaging",
    highlight: "Sleek hourglass silhouette in rich dark sheesham — sold as a graduated pair for layered styling.",
  },

  {
    id: 721,
    category: "candle-holders",
    name: "Hand-Carved Boho Pillar Candle Holder",
    image: "/products/candle-holders/h-2.webp",
    images: ["/products/candle-holders/h-2.webp"],
    material: "Mango Wood",
    finish: "Natural Brown with White Carved Inlay",
    size: "10 inch H x 4 inch Base Diameter",
    candleType: "Pillar Candle (3 inch diameter)",
    setOf: 1,
    usage: "Home Decor, Table Styling, Gift Sets",
    packaging: "Export Safe Packaging",
    highlight: "Lathe-turned column with hand-carved heart and arch motifs filled in white — a Bohemian statement piece.",
  },

  {
    id: 722,
    category: "candle-holders",
    name: "Rustic Turned Pillar Candle Stand",
    image: "/products/candle-holders/h-3.webp",
    images: ["/products/candle-holders/h-3.webp"],
    material: "Mango Wood",
    finish: "Natural Oil Finish, Exposed Grain",
    size: "4 inch H x 5 inch Base Diameter",
    candleType: "Pillar Candle (3 inch diameter)",
    setOf: 1,
    usage: "Dining Table, Garden Decor, Farmhouse Styling",
    packaging: "Export Safe Packaging",
    highlight: "Low-profile squat pedestal with bold natural grain — pairs beautifully with oversized pillar candles.",
  },

  {
    id: 723,
    category: "candle-holders",
    name: "White Marble & Gold Conical Tealight Holder Set",
    image: "/products/candle-holders/h-5.jpg",
    images: ["/products/candle-holders/h-5.jpg"],
    material: "White Marble + Brass Gold Inlay",
    finish: "Polished Marble with Gold Band & Diagonal Stripe",
    size: "Small: 4 inch H | Large: 6 inch H",
    candleType: "Tealight Candle",
    setOf: 2,
    usage: "Luxury Home Decor, Dining Table, Gift Sets",
    packaging: "Export Safe Packaging",
    highlight: "Tapered conical marble body accented with a brass gold ring and diagonal inlay stripe — modern luxury pair.",
  },

  {
    id: 724,
    category: "candle-holders",
    name: "Marble Base Gold Stem Taper Candle Holder Set",
    image: "/products/candle-holders/h-7.jpg",
    images: ["/products/candle-holders/h-7.jpg"],
    material: "White Marble Base + Brass Gold Stem",
    finish: "Polished Marble + Satin Gold Metal",
    size: "Small: 8 inch H | Medium: 10 inch H | Large: 12 inch H",
    candleType: "Taper Candle",
    setOf: 3,
    usage: "Mantelpiece, Dining Table, Wedding Decor",
    packaging: "Export Safe Packaging",
    highlight: "Rectangular marble cube base meets a slender gold brass stem — a trio of graduated heights for dramatic tablescaping.",
  },

  {
    id: 725,
    category: "candle-holders",
    name: "Slim Brass Taper Candle Holder Trio",
    image: "/products/candle-holders/h-8.jpg",
    images: ["/products/candle-holders/h-8.jpg"],
    material: "Iron with Brass/Gold Electroplating",
    finish: "Polished Satin Gold",
    size: "Small: 9 inch H | Medium: 12 inch H | Large: 15 inch H",
    candleType: "Taper Candle",
    setOf: 3,
    usage: "Living Room, Dining Table, Event Styling",
    packaging: "Export Safe Packaging",
    highlight: "Ultra-slim column design on a flat disc base — minimal Scandinavian silhouette in warm satin gold. Set of 3 graduated heights.",
  },

  {
    id: 726,
    category: "candle-holders",
    name: "Ceramic Chamber Candlestick with Ring Handle",
    image: "/products/candle-holders/h-9.jpg",
    images: ["/products/candle-holders/h-9.jpg"],
    material: "Glazed Ceramic",
    finish: "Sage Green Gloss Glaze",
    size: "5 inch diameter plate | 2.5 inch H column",
    candleType: "Taper Candle",
    setOf: 1,
    usage: "Dining Table, Bedside, Rustic & Cottagecore Decor",
    packaging: "Export Safe Packaging",
    highlight: "Traditional chamberstick form with a finger-ring handle — sage green glaze gives it an artisanal earthy character.",
  },

  {
    id: 727,
    category: "candle-holders",
    name: "Sculptural Ceramic Knot Taper Candle Holder Set",
    image: "/products/candle-holders/h-10.jpg",
    images: ["/products/candle-holders/h-10.jpg"],
    material: "Speckled Stoneware Ceramic",
    finish: "Cream / Off-White Matte Glaze",
    size: "Approx. 3.5 inch H each",
    candleType: "Taper Candle",
    setOf: 2,
    usage: "Table Styling, Shelf Decor, Artistic Display",
    packaging: "Export Safe Packaging",
    highlight: "Organic knotted rope forms hand-sculpted in speckled cream stoneware — each piece is a wearable sculpture for your table.",
  },

  {
    id: 728,
    category: "candle-holders",
    name: "Fluted Hourglass Pillar Candle Holder Set",
    image: "/products/candle-holders/h-11.jpg",
    images: ["/products/candle-holders/h-11.jpg"],
    material: "Elm / Light Oak Wood",
    finish: "Natural Unfinished, Hand-Sanded",
    size: "Small: 4 inch H | Large: 6 inch H",
    candleType: "Pillar Candle (3 inch diameter)",
    setOf: 2,
    usage: "Marble & Stone Table Styling, Dining Centrepiece",
    packaging: "Export Safe Packaging",
    highlight: "Vertical fluted ridges carved on a tapered hourglass base — light natural wood grain contrasts beautifully on marble surfaces.",
  },

  {
    id: 729,
    category: "candle-holders",
    name: "Stone Teardrop Tealight Holder",
    image: "/products/candle-holders/h-12.jpg",
    images: ["/products/candle-holders/h-12.jpg"],
    material: "Natural Stone / Concrete Composite",
    finish: "Textured Matte Stone Finish",
    size: "5 inch H x 4 inch W",
    candleType: "Tealight Candle",
    setOf: 1,
    usage: "Shelf Decor, Meditation Space, Bathroom Styling",
    packaging: "Export Safe Packaging",
    highlight: "Teardrop arch cut-out casts a warm amber glow — a zen-inspired tealight lantern in natural speckled stone.",
  },

];



